# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_prototype.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import random
from mplwidget import MplWidget, MplWidget3D
import sys, os

from PyQt5.QtWidgets import (
    QApplication,
    QDialog,
    QDialogButtonBox,
    QLabel,
    QMainWindow,
    QPushButton,
    QVBoxLayout,
)

sys.path.append(os.path.join(os.path.dirname(__file__), "..", "sensor"))
from Sensor_Driver import get_sensor_data
from Interpret_Sensor_Data import *

class CustomDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent=parent)

        self.setWindowTitle("HELLO!")

        QBtn = QDialogButtonBox.Ok | QDialogButtonBox.Cancel

        self.buttonBox = QDialogButtonBox(QBtn)
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)

        self.layout = QVBoxLayout()
        message = QLabel("Something happened, is that OK?")
        self.layout.addWidget(message)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 699)
        MainWindow.setDocumentMode(False)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1091, 651))
        self.tabWidget.setObjectName("tabWidget")

        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")

        self.swing_page_label = QtWidgets.QLabel(self.widget)
        self.swing_page_label.setGeometry(QtCore.QRect(390, 10, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.swing_page_label.setFont(font)
        self.swing_page_label.setAlignment(QtCore.Qt.AlignCenter)
        self.swing_page_label.setObjectName("swing_page_label")

        self.formLayoutWidget = QtWidgets.QWidget(self.widget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(610, 70, 231, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")

        self.club_stats_formlayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.club_stats_formlayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.club_stats_formlayout.setContentsMargins(0, 0, 0, 0)
        self.club_stats_formlayout.setHorizontalSpacing(16)
        self.club_stats_formlayout.setVerticalSpacing(14)
        self.club_stats_formlayout.setObjectName("club_stats_formlayout")

        self.club_speed_res_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.club_speed_res_label.setObjectName("club_speed_res_label")

        self.club_stats_formlayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.club_speed_res_label
        )
        # self.proj_distance_res_label_1 = QtWidgets.QLabel(self.formLayoutWidget)
        # self.proj_distance_res_label_1.setObjectName("proj_distance_res_label_1")

        # self.club_stats_formlayout.setWidget(
        #     2, QtWidgets.QFormLayout.FieldRole, self.proj_distance_res_label_1
        # )

        self.club_accel_res_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.club_accel_res_label.setObjectName("club_accel_res_label")

        self.club_stats_formlayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.club_accel_res_label
        )

        self.club_speed_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.club_speed_label.setFont(font)
        self.club_speed_label.setObjectName("club_speed_label")

        self.club_stats_formlayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.club_speed_label
        )

        self.club_accel_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.club_accel_label.setFont(font)
        self.club_accel_label.setObjectName("club_accel_label")

        self.club_stats_formlayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.club_accel_label
        )

        # self.proj_distance_label_1 = QtWidgets.QLabel(self.formLayoutWidget)
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # self.proj_distance_label_1.setFont(font)
        # self.proj_distance_label_1.setObjectName("proj_distance_label_1")

        # self.club_stats_formlayout.setWidget(
        #     2, QtWidgets.QFormLayout.LabelRole, self.proj_distance_label_1
        # )

        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 70, 426, 120))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.club_options_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.club_options_grid_layout.setSizeConstraint(
            QtWidgets.QLayout.SetMinimumSize
        )
        self.club_options_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.club_options_grid_layout.setHorizontalSpacing(6)
        self.club_options_grid_layout.setObjectName("club_options_grid_layout")

        self.calibrate_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.calibrate_button.setObjectName("calibrate_button")
        self.club_options_grid_layout.addWidget(self.calibrate_button, 2, 0, 1, 3)
        self.calibrate_button.clicked.connect(self.calibrate_system)

        self.club_length_unit_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.club_length_unit_combobox.setObjectName("club_length_unit_combobox")
        self.club_length_unit_combobox.addItem("")
        self.club_length_unit_combobox.addItem("")

        self.club_options_grid_layout.addWidget(
            self.club_length_unit_combobox, 1, 2, 1, 1
        )

        self.club_type_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.club_type_label.setFont(font)
        self.club_type_label.setObjectName("club_type_label")

        self.club_options_grid_layout.addWidget(self.club_type_label, 0, 0, 1, 1)

        self.club_length_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.club_length_label.setFont(font)
        self.club_length_label.setObjectName("club_length_label")

        self.club_options_grid_layout.addWidget(self.club_length_label, 1, 0, 1, 1)

        self.club_length_spinbox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.club_length_spinbox.setObjectName("club_length_spinbox")

        self.club_options_grid_layout.addWidget(self.club_length_spinbox, 1, 1, 1, 1)

        self.club_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.club_combobox.setObjectName("club_combobox")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")
        self.club_combobox.addItem("")

        self.club_options_grid_layout.addWidget(self.club_combobox, 0, 1, 1, 1)
        self.record_swing_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.record_swing_button.setObjectName("record_swing_button")
        self.club_options_grid_layout.addWidget(self.record_swing_button, 3, 0, 1, 3)

        # Click listener to plot dummy data
        self.record_swing_button.clicked.connect(self.update_graphs)

        self.MplWidget = MplWidget3D(self.widget)
        self.MplWidget.setGeometry(QtCore.QRect(50, 270, 480, 320))
        self.MplWidget.setObjectName("MplWidget")

        self.swing_plot_label = QtWidgets.QLabel(self.widget)
        self.swing_plot_label.setGeometry(QtCore.QRect(220, 230, 137, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.swing_plot_label.setFont(font)
        self.swing_plot_label.setAlignment(QtCore.Qt.AlignCenter)
        self.swing_plot_label.setObjectName("swing_plot_label")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(890, 80, 151, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")

        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )

        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )

        self.MplWidget_2 = MplWidget(self.widget)
        self.MplWidget_2.setGeometry(QtCore.QRect(560, 270, 480, 320))
        self.MplWidget_2.setObjectName("MplWidget_2")

        self.accel_plot_label = QtWidgets.QLabel(self.widget)
        self.accel_plot_label.setGeometry(QtCore.QRect(720, 230, 137, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accel_plot_label.setFont(font)
        self.accel_plot_label.setAlignment(QtCore.Qt.AlignCenter)
        self.accel_plot_label.setObjectName("accel_plot_label")

        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.ball_track_page_label = QtWidgets.QLabel(self.tab_2)
        self.ball_track_page_label.setGeometry(QtCore.QRect(390, 10, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ball_track_page_label.setFont(font)
        self.ball_track_page_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ball_track_page_label.setObjectName("ball_track_page_label")

        self.ball_cam_player = QtWidgets.QWidget(self.tab_2)
        self.ball_cam_player.setGeometry(QtCore.QRect(50, 270, 480, 320))
        self.ball_cam_player.setObjectName("ball_cam_player")

        self.ball_cam_label = QtWidgets.QLabel(self.tab_2)
        self.ball_cam_label.setGeometry(QtCore.QRect(220, 230, 137, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ball_cam_label.setFont(font)
        self.ball_cam_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ball_cam_label.setObjectName("ball_cam_label")

        self.MplWidget_4 = MplWidget(self.tab_2)
        self.MplWidget_4.setGeometry(QtCore.QRect(560, 270, 480, 320))
        self.MplWidget_4.setObjectName("MplWidget_4")

        self.ball_accel_label = QtWidgets.QLabel(self.tab_2)
        self.ball_accel_label.setGeometry(QtCore.QRect(720, 230, 137, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ball_accel_label.setFont(font)
        self.ball_accel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ball_accel_label.setObjectName("ball_accel_label")

        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(50, 80, 231, 111))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")

        self.ball_stats_layout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.ball_stats_layout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.ball_stats_layout.setContentsMargins(0, 0, 0, 0)
        self.ball_stats_layout.setHorizontalSpacing(16)
        self.ball_stats_layout.setVerticalSpacing(14)
        self.ball_stats_layout.setObjectName("ball_stats_layout")

        self.ball_init_velocity_res_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.ball_init_velocity_res_label.setObjectName("ball_init_velocity_res_label")

        self.ball_stats_layout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.ball_init_velocity_res_label
        )

        # self.proj_distance_res_label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        # self.proj_distance_res_label_2.setObjectName("proj_distance_res_label_2")
        # self.ball_stats_layout.setWidget(
        #     2, QtWidgets.QFormLayout.FieldRole, self.proj_distance_res_label_2
        # )

        self.launch_angle_res_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.launch_angle_res_label.setObjectName("launch_angle_res_label")

        self.ball_stats_layout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.launch_angle_res_label
        )
        self.ball_init_velocity_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ball_init_velocity_label.setFont(font)
        self.ball_init_velocity_label.setObjectName("ball_init_velocity_label")

        self.ball_stats_layout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.ball_init_velocity_label
        )

        self.launch_angle_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.launch_angle_label.setFont(font)
        self.launch_angle_label.setObjectName("launch_angle_label")

        self.ball_stats_layout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.launch_angle_label
        )

        # self.proj_distance_label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # self.proj_distance_label_2.setFont(font)
        # self.proj_distance_label_2.setObjectName("proj_distance_label_2")

        # self.ball_stats_layout.setWidget(
        #     2, QtWidgets.QFormLayout.LabelRole, self.proj_distance_label_2
        # )

        self.tabWidget.addTab(self.tab_2, "")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 20))
        self.menubar.setObjectName("menubar")

        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionTheme = QtWidgets.QAction(MainWindow)
        self.actionTheme.setObjectName("actionTheme")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionTheme_2 = QtWidgets.QAction(MainWindow)
        self.actionTheme_2.setObjectName("actionTheme_2")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")

        self.menuFile.addAction(self.actionTheme)
        self.menuFile.addAction(self.actionAbout_Us)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionTheme_2)
        self.menuEdit.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate

        # Setting text for all buttons/labels
        MainWindow.setWindowTitle(_translate("MainWindow", "Golf Swing Analyzer"))
        self.swing_page_label.setText(_translate("MainWindow", "Swing Analyzer"))
        self.club_speed_res_label.setText(_translate("MainWindow", "0 M/s"))
        # self.proj_distance_res_label_1.setText(_translate("MainWindow", "0 M"))
        self.club_accel_res_label.setText(_translate("MainWindow", "0 M/s<sup>2</sup>"))
        self.club_speed_label.setText(_translate("MainWindow", "Max Club Speed"))
        self.club_accel_label.setText(_translate("MainWindow", "Max Club Accel."))
        # self.proj_distance_label_1.setText(
        #     _translate("MainWindow", "Projected Distance")
        # )
        self.calibrate_button.setText(_translate("MainWindow", "Calibrate"))

        self.club_length_unit_combobox.setItemText(
            0, _translate("MainWindow", "Inches")
        )
        self.club_length_unit_combobox.setItemText(1, _translate("MainWindow", "Cm"))
        self.club_type_label.setText(_translate("MainWindow", "Club Type"))
        self.club_length_label.setText(_translate("MainWindow", "Club Length"))

        self.club_combobox.setItemText(0, _translate("MainWindow", "Driver"))
        self.club_combobox.setItemText(1, _translate("MainWindow", "1 Wood"))
        self.club_combobox.setItemText(2, _translate("MainWindow", "2 Wood"))
        self.club_combobox.setItemText(3, _translate("MainWindow", "3 Wood"))
        self.club_combobox.setItemText(4, _translate("MainWindow", "4 Wood"))
        self.club_combobox.setItemText(5, _translate("MainWindow", "5 Wood"))
        self.club_combobox.setItemText(6, _translate("MainWindow", "6 Wood"))
        self.club_combobox.setItemText(7, _translate("MainWindow", "7 Wood"))
        self.club_combobox.setItemText(8, _translate("MainWindow", "3-hybrid"))
        self.club_combobox.setItemText(9, _translate("MainWindow", "4-hybrid"))
        self.club_combobox.setItemText(10, _translate("MainWindow", "5-hybrid"))
        self.club_combobox.setItemText(11, _translate("MainWindow", "1 Iron"))
        self.club_combobox.setItemText(12, _translate("MainWindow", "2 Iron"))
        self.club_combobox.setItemText(13, _translate("MainWindow", "3 Iron"))
        self.club_combobox.setItemText(14, _translate("MainWindow", "4 Iron"))
        self.club_combobox.setItemText(15, _translate("MainWindow", "5 Iron"))
        self.club_combobox.setItemText(16, _translate("MainWindow", "6 Iron"))
        self.club_combobox.setItemText(17, _translate("MainWindow", "7 Iron"))
        self.club_combobox.setItemText(18, _translate("MainWindow", "8 Iron"))
        self.club_combobox.setItemText(19, _translate("MainWindow", "9 Iron"))
        self.club_combobox.setItemText(20, _translate("MainWindow", "Pitching Wedge"))
        self.club_combobox.setItemText(21, _translate("MainWindow", "Approach Wedge"))
        self.club_combobox.setItemText(22, _translate("MainWindow", "Sand Wedge"))
        self.club_combobox.setItemText(23, _translate("MainWindow", "Lob Wedge"))
        self.club_combobox.setItemText(24, _translate("MainWindow", "Putter"))

        self.record_swing_button.setText(_translate("MainWindow", "Record Swing"))
        self.swing_plot_label.setText(_translate("MainWindow", "Swing Plot"))
        self.accel_plot_label.setText(_translate("MainWindow", "Acceleration Plot"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.widget),
            _translate("MainWindow", "Swing Tracker"),
        )
        self.ball_track_page_label.setText(_translate("MainWindow", "Ball Tracker"))
        self.ball_cam_label.setText(_translate("MainWindow", "Ball Camera"))
        self.ball_accel_label.setText(_translate("MainWindow", "Ball Acceleration"))
        self.ball_init_velocity_res_label.setText(_translate("MainWindow", "0 M/s"))
        # self.proj_distance_res_label_2.setText(_translate("MainWindow", "0 M"))
        self.launch_angle_res_label.setText(_translate("MainWindow", "0 Deg"))
        self.ball_init_velocity_label.setText(
            _translate("MainWindow", "Initial Velocity")
        )
        self.launch_angle_label.setText(_translate("MainWindow", "Launch Angle"))
        # self.proj_distance_label_2.setText(
        #     _translate("MainWindow", "Projected Distance")
        # )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Ball Tracker")
        )

        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionTheme.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionTheme_2.setText(_translate("MainWindow", "Theme"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))

    def calibrate_system(self):

        res = self.find_club_angle(str(self.club_combobox.currentText()))
        res2 = self.club_length_spinbox.value()
        print(f"Loft angle of {str(self.club_combobox.currentText())}: {res} degrees")
        print(f"Length of club: {res2} {self.club_length_unit_combobox.currentText()}")

    def find_club_angle(self, club_type_str):
        club_angle_dict = {
            "Driver": 9.5,
            "1 Wood": 10,
            "2 Wood": 12,
            "3 Wood": 15,
            "4 Wood": 17,
            "5 Wood": 18,
            "6 Wood": 19,
            "7 Wood": 20,
            "3-hybrid": 21,
            "4-hybrid": 24,
            "5-hybrid": 27,
            "1 Iron": 14,
            "2 Iron": 17,
            "3 Iron": 20,
            "4 Iron": 23,
            "5 Iron": 26,
            "6 Iron": 29,
            "7 Iron": 33,
            "8 Iron": 37,
            "9 Iron": 41,
            "Pitching Wedge": 45,
            "Approach Wedge": 50,
            "Sand Wedge": 55,
            "Lob Wedge": 60,
            "Putter": 3,
        }

        return club_angle_dict[club_type_str]

    def update_graphs(self):
        # Parameters for swing recording
        seconds_to_record = 5
        in_file_name = "all_data.csv"
        out_file_name = "all_data_trimmed.csv"

        file = open(in_file_name,"r+")
        file.truncate(0)
        file.close()
        file = open(out_file_name,"r+")
        file.truncate(0)
        file.close()

        # Initiating recording script
        get_sensor_data(seconds_to_record, in_file_name, out_file_name)

        # Loading raw swing data
        raw_data = read_csv_data("all_data_trimmed.csv")

        # Processing swing data
        timeVsQuat, timeVsLinAccel, timeVsEulerAngs, timeVsInvQuat = processRawData(raw_data)

        # Grabbing club length from the GUI
        clubLen = float( self.club_length_spinbox.value())
        if clubLen == 0:
            clubLen = 45

        if self.club_length_unit_combobox.currentText() == "Inches":
            clubLen*=2.54
            clubLen/=100
        
        else:
            clubLen/=100

        # Interpreting quaterions to find position
        xs, ys, zs = plotQuats(timeVsQuat, clubLen)
        
        

        ######### Graph 1 #############
        
        # Plotting swing
        self.MplWidget.canvas.axes.clear()
        self.MplWidget.canvas.axes.plot3D(xs, ys, zs, "gray")
        self.MplWidget.canvas.axes.scatter3D(
            xs, ys, zs, color = "green"
        )
        self.MplWidget.canvas.draw()

        ######### Graph 2 #############
        x1, y1, y2, y3 = 0, 0, 0, 0
        x1, y1, y2, y3 = findAccel(timeVsLinAccel)

      
        # dts = [t-x1[0] for t in x1]
        # dts = np.zeros_like(x1)
        dts = [x1[i+1]-x1[i] for i in range(len(x1)-1)]
        

        maxAccel = findMaxAccel(x1, y1, y2, y3)
        self.club_accel_res_label.setText(f'{maxAccel:.2f} M/s<sup>2</sup>')
        
        maxSpeed = findMaxSpeed(dts, xs, ys, zs)
        self.club_speed_res_label.setText(f'{maxSpeed:.2f} M/s')


        x2 = [t-x1[0] for t in x1]
        self.MplWidget_2.canvas.axes.clear()
        self.MplWidget_2.canvas.axes.plot(x2, y1, label="x accel")
        self.MplWidget_2.canvas.axes.plot(x2, y2, label="y accel")
        self.MplWidget_2.canvas.axes.plot(x2, y3, label="z accel")
        self.MplWidget_2.canvas.axes.legend()
        self.MplWidget_2.canvas.draw()
       


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
